### ISSUE TITLE
Unexpected Colon in `Things that start with IIIIIIII`

### ISSUE THREAD

**Issue by MisterPoppet** [themccallister/craft-snippets#1]
After installing your plugin, Atom throws up this error:

```
Failed to load snippets from '/Users/user/.atom/packages/craft-snippets/snippets/i.cson'
/Users/user/.atom/packages/craft-snippets/snippets/i.cson: unexpected :
```

**Comment by jasonmccallister** [comment]
Thank you for reporting this! I will look into it soon.

**Comment by boboldehampsink** [comment]
I'm experiencing this also

**Comment by jasonmccallister** [comment]
@boboldehampsink have you installed the package again? I'm having a few issues with the APM locally that I am working through. 

I will publish a point release asap.

Also, I'm going to leave this issue open until I can push the new package.

**Comment by jasonmccallister** [comment]
Closing this out, corrected and published the package in Atom and also added basic twig support.
